sudo: false
language: python

python:
  - '3.5'
  - '3.6'

matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true

install:
  - pip install poetry
  - poetry install

script:
  - pycodestyle logconf.py
  - pylint -E logconf
  - pytest
